- name:  role
  hosts: all
  become: true
  vars:
    consul_version: "1.18.0"
    consul_config:
      datacenter: "molecule"
      log_level: "info"
      data_dir: "/var/lib/consul/"
      bind_addr: "0.0.0.0"
      ui_config:
        enabled: true
      enable_local_script_checks: true
      server: true
      bootstrap_expect: 1

    consul_configs:
      log_level:
        log_level: "info"

    consul_services:
      example:
        service:
          id: "example"
          name: "example"
          port: 12345
          check:
            id: "example"
            name: "example"
            args:
              - "/opt/consul/script.d/example.sh"
            interval: "30s"

    consul_scripts:
      example: |
        #! /usr/bin/env bash
        echo "example"

  collections:
    - nahsilabs.hashistack

  tasks:
    - name: Run consul role
      include_role:
        name: consul
