- name: restart consul
  systemd_service:
    name: consul
    state: restarted
    daemon_reload: true
  when: not skip_handlers

- name: restart systemd-resolved
  systemd_service:
    name: systemd-resolved
    state: restarted
    daemon_reload: true
