- name: create vault system group
  group:
    name: "{{ vault_group }}"
    system: true
    state: present

- name: create vault system user
  user:
    name: "{{ vault_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ vault_group }}"
    create_home: false
    state: present

- name: create vault directories
  file:
    path: "{{ dir.value.path }}"
    state: directory
    owner: "{{ dir.group | default('vault') }}"
    group: "{{ dir.group | default('vault') }}"
    mode: "{{ dir.value.mode | default(755) }}"
  loop: "{{ vault_dirs | dict2items }}"
  loop_control:
    loop_var: dir
    label: "{{ dir.key }}"

- name: install unzip
  apt:
    name: "unzip"
    install_recommends: false
    update_cache: true
    autoclean: true
    autoremove: true
    state: present

- name: download vault archive
  get_url:
    url: "{{ _archive_url }}"
    dest: "{{ vault_dirs.archives.path }}/{{ _archive }}"
    checksum: "sha256:{{ _archive_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2

- name: unpack vault
  unarchive:
    src: "{{ vault_dirs.archives.path }}/{{ _archive }}"
    dest: "/usr/bin/"
    include: ["vault"]
    remote_src: true
  notify: restart vault

- name: create vault config
  tags: config
  copy:
    content: "{{ vault_config | to_nice_json }}"
    dest: "{{ vault_dirs.main.path }}/vault.json"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0640
  notify: restart vault

- name: create vault unit file
  tags: config
  copy:
    content: "{{ vault_unit }}"
    dest: "/etc/systemd/system/vault.service"
    owner: root
    group: root
    mode: 0755
  notify: restart vault

- name: enable vault
  systemd:
    name: vault
    enabled: true
    daemon_reload: true
  when: not skip_enable
