- name: Prepare
  become: true
  hosts: all
  tasks:
    - name: create vault directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /opt/vault/config.d

    - name: create dummy files
      file:
        path: "{{ item }}"
        state: touch
      loop:
        - /opt/vault/config.d/dummy.json
