skip_handlers: false
skip_enable: false

vault_download_url: "https://releases.hashicorp.com"

vault_configs: {}

vault_user: "vault"
vault_group: "vault"

vault_dir: "/opt/vault"
vault_dirs:
  main:
    path: "{{ vault_dir }}"
  configs:
    path: "{{ vault_dir }}/config.d"
  certs:
    path: "{{ vault_dir }}/certs"
  archives:
    path: "{{ vault_dir }}/archives"
  data:
    path: "/var/lib/vault"
    mode: "u=rwX,g=rX,o="
  logs:
    path: "/var/log/vault"

vault_unit: |
  [Unit]
  Description="HashiCorp Vault - A platform for managing secrets"
  Documentation=https://www.vaultproject.io/docs/
  Requires=network-online.target
  After=network-online.target
  StartLimitIntervalSec=60
  StartLimitBurst=3

  [Service]
  User={{ vault_user }}
  Group={{ vault_group }}
  ProtectSystem=full
  ProtectHome=read-only
  PrivateTmp=yes
  PrivateDevices=yes
  SecureBits=keep-caps
  AmbientCapabilities=CAP_IPC_LOCK
  CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
  NoNewPrivileges=yes
  ExecStart=/usr/bin/vault server -config={{ vault_dir }}/vault.json -config={{ vault_dirs.configs.path }}
  ExecReload=/bin/kill --signal HUP $MAINPID
  KillMode=process
  KillSignal=SIGINT
  Restart=on-failure
  RestartSec=5
  TimeoutStopSec=30
  StartLimitInterval=60
  StartLimitBurst=3
  LimitNOFILE=65536
  LimitMEMLOCK=infinity

  [Install]
  WantedBy=multi-user.target
